# Version 0.11
---

- hosts: OneViewManagedBmcs
  connection: local
  gather_facts: no
  vars:
      ilo_user: demopaq
      ilo_pass: password

  tasks:
  # In a real/physical infrastructure, you must login first
  #- name: Login
  #  shell: >
  #    ilorest --nologo --cache-dir {{ cache_dir }}
  #    login {{ inventory_hostname }} -u {{ ilo_user }}  -p {{ ilo_pass }}

  - name: get Indicator LEDs status
    shell: >
      /usr/sbin/ilorest --nologo --cache-dir {{ cache_dir }}
      get IndicatorLED
      --selector=Chassis.
    register: IndicatorLedStatus

  - debug:
        msg: "{{ IndicatorLedStatus.stdout_lines }}"

  - name: Toggle Indicator LEDs
    shell: >
      /usr/sbin/ilorest --nologo --cache-dir {{ cache_dir }}
      set IndicatorLED="{{ 'Lit' if 'Off' in IndicatorLedStatus.stdout else 'Off' }}"
      --selector=Chassis. #--commit
    register: Ret

  - debug:
        msg: "{{ Ret.stderr_lines }}"
  
  - name: get Indicator LEDs status
    shell: >
      ilorest --nologo --cache-dir {{ cache_dir }}
      get IndicatorLED 
      --selector=Chassis.
    register: IndicatorLedStatus

  - debug:
        msg: "{{ IndicatorLedStatus.stdout_lines }}"
       

  - name: Refresh cache
    shell: ilorest --nologo --cache-dir {{ cache_dir }} select Chassis. --refresh

  # In a real/physical infrastructure, you should always logout.
  #
  # If you uncomment the following two lines, you will be able to run this playbook once.
  # Then, the iLOrest cache will be deleted and you will have to run the
  # Environment Preparation cell to re-create the cache and be able to run again this playbook.
  #- name: Logout
  #  shell: ilorest --nologo --cache-dir {{ cache_dir }} logout

